-include .env

build:; forge build

deploy-sepolia:
	forge script script/DeployFundMe --rpc-url $(SEPOLIA_RPC_URL) --private-ket $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv